// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxaVceIoCtuOM2iCPmuZBWTUgEEyMZ00A',
    appId: '1:386667380076:web:beade9fd494325c3688749',
    messagingSenderId: '386667380076',
    projectId: 'fyp-project-98f0f',
    authDomain: 'fyp-project-98f0f.firebaseapp.com',
    storageBucket: 'fyp-project-98f0f.appspot.com',
    measurementId: 'G-ELTB7Z1Q3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzdYF-u3_Yzdd-ZpRMxQwC0LEIiwLNG0',
    appId: '1:386667380076:android:d270c98f82c36d44688749',
    messagingSenderId: '386667380076',
    projectId: 'fyp-project-98f0f',
    storageBucket: 'fyp-project-98f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgU4WHa9wQD1v0H49VNzvNIgL3tPNwwwM',
    appId: '1:386667380076:ios:662aced19c06b655688749',
    messagingSenderId: '386667380076',
    projectId: 'fyp-project-98f0f',
    storageBucket: 'fyp-project-98f0f.appspot.com',
    iosClientId: '386667380076-in5ligvkvh4m3s0lcafte56tcuefnae9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypPrototype',
  );
}
